apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logcollectors.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: LogCollector
    listKind: LogCollectorList
    plural: logcollectors
    singular: logcollector
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            s3:
              properties:
                bucketName:
                  description: Name of the S3 bucket to send logs
                  type: string
                bucketPath:
                  description: Path in the S3 bucket where to send logs
                  type: string
                region:
                  description: AWS Region of the S3 bucket
                  type: string
              required:
              - region
              - bucketName
              - bucketPath
              type: object
            syslog:
              properties:
                endpoint:
                  description: 'Endpoint where to seen syslog. exmple: tcp://1.2.3.4:601'
                  type: string
                packetsize:
                  description: PacketSize is only needed if you notice long logs being
                    truncated. The default for the fluentd output plugin is 1024.
                  format: int32
                  type: integer
              required:
              - endpoint
              type: object
          type: object
        status:
          properties:
            state:
              description: State indicates the state of the daemonset by the LogCollector
                controller
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
