apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installations.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: Installation
    listKind: InstallationList
    plural: installations
    singular: installation
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            calicoNetwork:
              description: CalicoNetwork specifies configuration options when using
                Calico provided pod networking.
              properties:
                ipPools:
                  description: 'IPPools contains a list of IP pools to use for allocating
                    pod IP addresses. For now, a maximum of one IP pool is supported.
                    Default: 192.168.0.0/16'
                  items:
                    properties:
                      cidr:
                        description: CIDR contains the CIDR of the IP Pool.
                        type: string
                      encapsulation:
                        description: Encapsulation specifies the encapsulation type
                          that will be used with the IP Pool. VXLAN is the default.
                        enum:
                        - IPIPCrossSubnet
                        - IPIP
                        - VXLAN
                        - None
                        type: string
                      natOutgoing:
                        description: NATOutgoing specifies if NAT will be enabled
                          or disabled for outgoing traffic. Enabled is the default.
                        enum:
                        - Enabled
                        - Disabled
                        type: string
                      nodeSelector:
                        description: NodeSelector specifies the node selector that
                          will be set for the IP Pool. Default is 'all()'.
                        type: string
                    required:
                    - cidr
                    type: object
                  type: array
              type: object
            imagePullSecrets:
              description: ImagePullSecrets is an array of references to Docker registry
                pull secrets.
              items:
                type: object
              type: array
            kubernetesProvider:
              description: KubernetesProvider specifies which platform this cluster
                is running on. Operator will do it's best to autodetect and set this.
                But can be overridden here.
              type: string
            registry:
              description: 'Registry is the default Docker registry used for component
                Docker images. Default: docker.io/'
              type: string
            variant:
              description: 'Variant is the product to install - one of Calico or TigeraSecureEnterprise
                Default: Calico'
              type: string
          type: object
        status:
          properties:
            variant:
              description: Variant is the installed product - one of Calico or TigeraSecureEnterprise
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
