apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator
  template:
    metadata:
      labels:
        name: operator
    spec:
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
      serviceAccountName: operator
      hostNetwork: true
      containers:
        - name: operator
          # Replace this with the built image name
          image: caseydavenport/operator
          command:
          - operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operator"
