title: release-v3.19
components:
  typha:
    version: release-v3.19
  calico/node:
    version: release-v3.19
  calico/cni:
    version: release-v3.19
  calico/kube-controllers:
    version: release-v3.19
  flexvol:
    version: release-v3.19
